spring.application.name=QuanLyLinhKien
# Th\u00f4ng tin k\u1ebft n\u1ed1i SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLyThietBiMayTinh;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# C\u1ea5u h\u00ecnh Hibernate JPA (R\u1ea5t ti\u1ec7n l\u1ee3i cho vi\u1ec7c chuy\u1ec3n code t\u1eeb C# sang)
# ddl-auto=update: T\u1ef1 \u0111\u1ed9ng c\u1eadp nh\u1eadt ho\u1eb7c t\u1ea1o b\u1ea3ng m\u1edbi trong SQL d\u1ef1a tr\u00ean c\u00e1c class Java c\u1ee7a b\u1ea1n
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true